#==========================================================================
# https://github.com/xzhhzx222/actions-builder
#==========================================================================

name: Source Code Compiler

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  CONFIG_FILE: shells/.config.compile
  DIY_P1_SH: shells/diy-part1.sh
  DIY_P2_SH: shells/diy-part2.sh
  TZ: Asia/Shanghai
  CCACHE_DIR: /workdir/openwrt/.ccache
  CUSTOM_DIR: package/xzhhzx222

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        target:
          - "v25.12.1"
          - "v24.10.6"

    name: Compile ${{ matrix.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Free Disk Space (Ubuntu)
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle"
          rm_cmd: "rmz"  # Use 'rmz' for faster deletion (default: 'rm')
          rmz_version: "3.1.1"  # Required when rm_cmd is 'rmz'
          testing: false

      - name: Create virtual disk for extended storage
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /workdir
          sudo mount /dev/github/runner /workdir
          sudo chown -R runner:runner /workdir
          df -Th

      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone $REPO_URL -b ${{ matrix.target }} --single-branch --filter=blob:none openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "::group::docker system prune"
          sudo docker system prune --all --force --volumes
          echo "::endgroup::"

          echo "::group::install depends"
          sudo apt-get -y update
          sudo apt-get -y install $(cat shells/depends.compile)
          sudo apt-get -y autoremove --purge
          sudo apt-get -y clean
          echo "::endgroup::"

          mkdir -p "openwrt/.ccache" "openwrt/${CUSTOM_DIR}"

      - name: Setup cache
        uses: actions/cache@v5
        with:
          path: |
            openwrt/.ccache
            openwrt/dl
          # key: cache-compile-${{ matrix.target }}-${{ hashFiles('shells/.config.compile') }}
          key: cache-compile-${{ matrix.target }}-${{ hashFiles(env.CONFIG_FILE) }}
          restore-keys: |
            cache-compile-${{ matrix.target }}-

      - name: Load custom feeds
        run: |
          chmod +x $DIY_P1_SH
          cd openwrt

          echo "::group::bash ${DIY_P1_SH}"
          $GITHUB_WORKSPACE/$DIY_P1_SH
          echo "::endgroup::"

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [ -e files ] && mv -vf files openwrt/files
          [ -e $CONFIG_FILE ] && mv -vf $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt

          echo "::group::bash ${DIY_P2_SH}"
          $GITHUB_WORKSPACE/$DIY_P2_SH
          echo "::endgroup::"

      - name: Download package
        id: package
        run: |
          cd openwrt

          echo "::group::make defconfig"
          make defconfig
          echo "::endgroup::"

          echo "::group::make download"
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          echo "::endgroup::"

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          ccache -z

          echo "::group::complie with $(nproc) threads"
          make -j$(($(nproc) + 1)) || make -j1 V=s
          echo "::endgroup::"

          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Check space usage
        if: (!cancelled())
        run: |
          df -hT
          echo -e "ccache statistics:"
          ccache -s 2>/dev/null
          echo -e "ccache directory size:"
          du -sh openwrt/.ccache 2>/dev/null || echo "No ccache directory found."
          du -sh openwrt/dl 2>/dev/null || echo "No dl directory found."

          echo "::group::targets directory list"
          ls -lah openwrt/bin/targets/*/*/ 2>/dev/null || \
            echo "No targets found."
          echo "::endgroup::"

      - name: Organize files
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          ls -lh sha256sums
          sed -i "/kernel/d" sha256sums
          sed -i "/rootfs/d" sha256sums
          # sed -i 's/immortalwrt/openwrt/g' sha256sums
          rm -vf *kernel.bin
          rm -vf *rootfs*.gz
          for filename in immortalwrt-*; do
            [ -e "${filename}" ] && \
              mv -v "${filename}" "openwrt-${filename#immortalwrt-}"
          done
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Generate release tag
        id: tag
        if: steps.organize.outputs.status == 'success' && !cancelled()
        run: |
          echo "release_name=$(date +"%y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          touch release.txt
          echo "* **Method:** ${{ github.workflow }}" >> release.txt
          echo "* **Resource:** [ImmortalWrt ${{ matrix.target }}](${REPO_URL}/tree/${{ matrix.target }})" >> release.txt
          echo "* **Release on:** $(date)" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v3
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          name: ImmortalWrt_${{ steps.tag.outputs.release_name }}
          tag_name: ${{ env.FILE_DATE }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*
          make_latest: true

      - name: Delete releases
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 2
          gh_token: ${{ secrets.GITHUB_TOKEN }}
