#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older workflows

on:
  # repository_dispatch:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'

env:
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    # if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    permissions:
      contents: write
      actions: write

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v6
      #
      # - name: Initialize the environment
      #   id: init
      #   env:
      #     DEBIAN_FRONTEND: noninteractive
      #   run: |
      #     sudo timedatectl set-timezone "${TZ}"
      #     echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_workflows: true
          workflows_keep_day: 14
          gh_token: ${{ secrets.GITHUB_TOKEN }}
