#==========================================================================
# https://github.com/xzhhzx222/actions-builder
#==========================================================================

name: TEST

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    name: TEST

    steps:
      - name: Checkout Public
        uses: actions/checkout@v7

      - name: Checkout Private
        uses: actions/checkout@v7
        with:
          repository: xzhhzx222/actions-private
          token: ${{ secrets.MY_PAT }}
          path: private
          sparse-checkout: files

      - name: Checkout Result
        run: |
          df -Th
          ls -lah $GITHUB_WORKSPACE
          ls -lah $GITHUB_WORKSPACE/private
